# Generated by Django 6.0.3 on 2026-03-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='Category',
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ManyToManyField(to='story_blog.category'),
        ),
    ]
