# Generated by Django 6.0.3 on 2026-03-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0002_remove_story_category_story_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='storypart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_parts/'),
        ),
    ]
