# Generated by Django 6.0.3 on 2026-03-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0006_shortstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('concept', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_ideas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ManyToManyField(blank=True, to='story_blog.category')),
            ],
        ),
    ]
